name: fd_template_creator
description: A sample command-line application.
version: 1.0.0
homepage: https://github.com/Floating-Dartists/fd_template_creator
environment:
  sdk: '>=2.16.1 <3.0.0'

dev_dependencies:
  lint: ^1.8.2
  test: ^1.16.0
dependencies:
  yaml: ^3.1.0
