name: Test workflow

on:
  push

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1
      - run: dart pub get
      - name: Analyze project source
        run: dart analyze
        working-directory: ./lib
  test:
    needs: analyze
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: dart-lang/setup-dart@v1
    - run: dart pub get
    - name: Test
      run: dart test
  run:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v1.5.3
    - run: flutter packages get
    - name: Run
      run: dart run ../bin/fd_template_creator.dart
      working-directory: ./example